### PR TITLE
LPS-83841 SF - packageinfo

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by ahdezma** [comment]
ci:test

**Comment by ahdezma** [comment]
ci:stop

**Comment by ahdezma** [comment]
ci:test

**Comment by ahdezma** [comment]
ci:stop

**Comment by ahdezma** [comment]
ci:test:sf

**Comment by ahdezma** [comment]
ci:test:relevant

**Comment by juliocamarero** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/62188

**Pull request closed without merging**
